# ERA5 Temperature Downloader Configuration

# File paths
paths:
  base_dir: "/path/to/your/data/directory"  # Change this to your data directory

# Geographic area of interest [North, West, South, East] in decimal degrees
# Current example covers Italy
area: [47.0, 13.0, 39.0, 20.0]

# Download settings
download_delay: 2  # seconds between downloads (be respectful to CDS)

# Time period to download
period:
  start_year: 1979
  start_month: 1
  end_year: 2024
  end_month: 12

# Example configurations for different regions:
# Mediterranean Basin: [45.0, -10.0, 30.0, 40.0]
# Sahel Region: [18.0, -20.0, 12.0, 22.0]
# Spain: [43.9, -9.3, 35.9, 3.3]
